/**
 * Firestore Config API Routes
 * Admin visibility into system config collections + health stats.
 * TRK-505 through TRK-522 (Firestore Config Admin Panel sprint)
 */

import { Router, type Request, type Response } from 'express'
import { getFirestore, FieldValue } from 'firebase-admin/firestore'
import { successResponse, errorResponse, param } from '../lib/helpers.js'
import type { FirestoreConfigCollectionsData, PlatformStatusData, FirestoreHealthData, FirestoreConfigDocResult, FirestoreConfigDeleteResult, FirestoreConfigDeleteCollectionResult } from '@tomachina/core'

export const firestoreConfigRoutes = Router()

// ─── Whitelist: config collections exposed by default ───
const CONFIG_COLLECTIONS = [
  'acf_config',
  'spark_config',
  'specialist_configs',
  'territories',
  'comp_grids',
  'comp_grid_history',
  'wire_definitions',
  'source_registry',
  'tool_registry',
  'atlas_formats',
  'format_library',
  'org',
] as const

// ─── TRK-507: Wiring status — auto-detected at build time ───
// Generated by: npx tsx services/api/src/scripts/detect-wiring.ts
// Runs as pre-build hook. Do NOT edit by hand.
import { readFileSync } from 'fs'
import { resolve } from 'path'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let PLATFORM_STATUS: any = {}
let WIRING_STATUS: Record<string, { status: string; backend: string; frontend: string; backend_endpoints?: number }> = {}
try {
  const wiringPath = resolve(__dirname, '..', 'generated', 'wiring-status.json')
  PLATFORM_STATUS = JSON.parse(readFileSync(wiringPath, 'utf-8'))
  // Support both old format (root = collections) and new format (root.collections)
  WIRING_STATUS = PLATFORM_STATUS.collections || PLATFORM_STATUS
} catch {
  console.warn('[firestore-config] wiring-status.json not found — run detect-wiring.ts')
}

// Queue collections for health dashboard
const QUEUE_COLLECTIONS = ['intake_queue', 'approval_queue'] as const

// ─── Helpers ───
function detectFieldType(value: unknown): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'boolean') return 'boolean'
  if (typeof value === 'number') return 'number'
  if (typeof value === 'string') return 'string'
  if (Array.isArray(value)) return 'array'
  if (typeof value === 'object') return 'object'
  return 'unknown'
}

function buildTypeSummary(data: Record<string, unknown>): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const val of Object.values(data)) {
    const t = detectFieldType(val)
    counts[t] = (counts[t] || 0) + 1
  }
  return counts
}

function isValidSnakeCase(name: string): boolean {
  return /^[a-z][a-z0-9_]*$/.test(name)
}

// ─── TRK-507: GET /collections — with wiring status ───
firestoreConfigRoutes.get('/collections', async (_req: Request, res: Response) => {
  try {
    const db = getFirestore()
    const snapshots = await Promise.all(
      CONFIG_COLLECTIONS.map(name => db.collection(name).get())
    )

    const results = CONFIG_COLLECTIONS.map((name, i) => {
      const snap = snapshots[i]
      const docs = snap.docs.map(doc => {
        const data = doc.data() as Record<string, unknown>
        return {
          id: doc.id,
          fieldCount: Object.keys(data).length,
          typeSummary: buildTypeSummary(data),
          updatedAt: (data.updated_at as string) || (data.updatedAt as string) || null,
          data,
        }
      })
      return {
        name,
        count: snap.size,
        docs,
        wiring: WIRING_STATUS[name] || { status: 'placeholder' as const, backend: '', frontend: '' },
      }
    })

    res.json(successResponse<FirestoreConfigCollectionsData>(results as unknown as FirestoreConfigCollectionsData))
  } catch (err) {
    console.error('GET /api/firestore-config/collections error:', err)
    res.status(500).json(errorResponse('Failed to load config collections'))
  }
})

// ─── Platform Status — all 5 asset types from build-time scan ───
firestoreConfigRoutes.get('/platform-status', async (_req: Request, res: Response) => {
  try {
    res.json(successResponse<PlatformStatusData>({
      api_routes: PLATFORM_STATUS.api_routes || {},
      cloud_functions: PLATFORM_STATUS.cloud_functions || [],
      env_vars: PLATFORM_STATUS.env_vars || [],
      hookify_rules: PLATFORM_STATUS.hookify_rules || [],
      scan_stats: PLATFORM_STATUS.scan_stats || {},
    } as unknown as PlatformStatusData))
  } catch (err) {
    console.error('GET /api/firestore-config/platform-status error:', err)
    res.status(500).json(errorResponse('Failed to load platform status'))
  }
})

// ─── TRK-521: GET /health — with per-query resilience ───
firestoreConfigRoutes.get('/health', async (_req: Request, res: Response) => {
  try {
    const db = getFirestore()

    const safeCount = async (query: Promise<{ data: () => { count: number } }>): Promise<number> => {
      try { return (await query).data().count } catch { return -1 }
    }

    const [activeClients, households, users, activeAccounts, queueResults, missingAgent, missingHousehold, noAccounts] = await Promise.all([
      safeCount(db.collection('clients').where('status', '==', 'Active').count().get()),
      safeCount(db.collection('households').count().get()),
      safeCount(db.collection('users').count().get()),
      safeCount(db.collectionGroup('accounts').count().get()),
      Promise.all(QUEUE_COLLECTIONS.map(async name => {
        try {
          const snap = await db.collection(name).count().get()
          return { name, count: snap.data().count }
        } catch { return { name, count: -1 } }
      })),
      safeCount(db.collection('clients').where('status', '==', 'Active').where('agent_id', '==', '').count().get()),
      safeCount(db.collection('clients').where('status', '==', 'Active').where('household_id', '==', '').count().get()),
      safeCount(db.collection('clients').where('status', '==', 'Active').where('account_count', '==', 0).count().get()),
    ])

    const queues: Record<string, number> = {}
    for (const q of queueResults) queues[q.name] = q.count

    res.json(successResponse<FirestoreHealthData>({
      collections: { active_clients: activeClients, households, users, active_accounts: activeAccounts },
      queues,
      dataGaps: { missing_agent: missingAgent, missing_household: missingHousehold, no_accounts: noAccounts },
    } as unknown as FirestoreHealthData))
  } catch (err) {
    console.error('GET /api/firestore-config/health error:', err)
    res.status(500).json(errorResponse('Failed to load health stats'))
  }
})

// ─── TRK-505/512: PUT /:collection/:docId — create/update + _delete_fields ───
firestoreConfigRoutes.put('/:collection/:docId', async (req: Request, res: Response) => {
  try {
    const collectionName = param(req.params.collection)
    const docId = param(req.params.docId)

    if (!isValidSnakeCase(collectionName)) {
      res.status(400).json(errorResponse('Collection name must be snake_case'))
      return
    }

    const db = getFirestore()
    const docRef = db.collection(collectionName).doc(docId)
    const existing = await docRef.get()
    const body = req.body as Record<string, unknown>
    const now = new Date().toISOString()

    // TRK-512: Handle _delete_fields — remove fields using FieldValue.delete()
    const deleteFields = body._delete_fields as string[] | undefined
    if (deleteFields && deleteFields.length > 0) {
      const deletes: Record<string, unknown> = {}
      for (const f of deleteFields) {
        if (f !== 'created_at' && f !== 'updated_at') {
          deletes[f] = FieldValue.delete()
        }
      }
      if (existing.exists && Object.keys(deletes).length > 0) {
        await docRef.update({ ...deletes, updated_at: now })
      }
    }
    delete body._delete_fields

    // Create or update remaining fields
    if (existing.exists) {
      await docRef.update({ ...body, updated_at: now })
    } else {
      await docRef.set({ ...body, created_at: now, updated_at: now })
    }

    const updated = await docRef.get()
    const isWhitelisted = CONFIG_COLLECTIONS.includes(collectionName as typeof CONFIG_COLLECTIONS[number])
    res.json(successResponse<FirestoreConfigDocResult>({
      id: updated.id,
      ...updated.data(),
      _meta: { wired: isWhitelisted, collection: collectionName },
    } as unknown as FirestoreConfigDocResult))
  } catch (err) {
    console.error('PUT /api/firestore-config/:collection/:docId error:', err)
    res.status(500).json(errorResponse('Failed to save config document'))
  }
})

// ─── TRK-505: DELETE /:collection/:docId — delete single document ───
firestoreConfigRoutes.delete('/:collection/:docId', async (req: Request, res: Response) => {
  try {
    const collectionName = param(req.params.collection)
    const docId = param(req.params.docId)

    if (!isValidSnakeCase(collectionName)) {
      res.status(400).json(errorResponse('Invalid collection name'))
      return
    }

    const db = getFirestore()
    const docRef = db.collection(collectionName).doc(docId)
    const existing = await docRef.get()

    if (!existing.exists) {
      res.status(404).json(errorResponse(`Document "${docId}" not found in ${collectionName}`))
      return
    }

    await docRef.delete()
    res.json(successResponse<FirestoreConfigDeleteResult>({ deleted: { collection: collectionName, docId } } as unknown as FirestoreConfigDeleteResult))
  } catch (err) {
    console.error('DELETE /api/firestore-config/:collection/:docId error:', err)
    res.status(500).json(errorResponse('Failed to delete document'))
  }
})

// ─── TRK-506: DELETE /:collection — delete all docs (type-to-confirm) ───
firestoreConfigRoutes.delete('/:collection', async (req: Request, res: Response) => {
  try {
    const collectionName = param(req.params.collection)
    const confirm = (req.query.confirm as string) || ''

    if (!isValidSnakeCase(collectionName)) {
      res.status(400).json(errorResponse('Invalid collection name'))
      return
    }

    if (confirm !== collectionName) {
      res.status(400).json(errorResponse(`Type-to-confirm failed. Send ?confirm=${collectionName} to delete.`))
      return
    }

    const db = getFirestore()
    const snap = await db.collection(collectionName).get()

    if (snap.empty) {
      res.json(successResponse<FirestoreConfigDeleteCollectionResult>({ deleted: { collection: collectionName, count: 0 } } as unknown as FirestoreConfigDeleteCollectionResult))
      return
    }

    // Batch delete (max 500 per batch)
    let deleted = 0
    const batches: FirebaseFirestore.WriteBatch[] = [db.batch()]
    let batchIdx = 0
    let batchCount = 0

    for (const doc of snap.docs) {
      batches[batchIdx].delete(doc.ref)
      batchCount++
      deleted++
      if (batchCount >= 500) {
        batchIdx++
        batches.push(db.batch())
        batchCount = 0
      }
    }

    await Promise.all(batches.map(b => b.commit()))
    res.json(successResponse<FirestoreConfigDeleteCollectionResult>({ deleted: { collection: collectionName, count: deleted } } as unknown as FirestoreConfigDeleteCollectionResult))
  } catch (err) {
    console.error('DELETE /api/firestore-config/:collection error:', err)
    res.status(500).json(errorResponse('Failed to delete collection'))
  }
})
