"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NBX_ANNUITY_CONFIG = void 0;
const PK = 'NBX_ANNUITY';
const now = new Date().toISOString();
exports.NBX_ANNUITY_CONFIG = {
    pipeline: {
        pipeline_key: PK,
        pipeline_name: 'NBX - Annuity',
        description: 'New business processing for annuity applications (FIA, MYGA)',
        portal: 'PRODASHX',
        domain: 'ANNUITY',
        default_view: 'KANBAN',
        icon: 'savings',
        status: 'active',
        created_at: now,
        updated_at: now,
    },
    stages: [
        {
            pipeline_key: PK,
            stage_id: 'new',
            stage_name: 'New',
            stage_description: 'New annuity case intake',
            stage_order: 10,
            stage_color: 'var(--stage-new)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            stage_name: 'Intake',
            stage_description: 'Collect current statements, data, and schedule meeting',
            stage_order: 20,
            stage_color: 'var(--stage-intake)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            stage_name: 'Analysis',
            stage_description: 'Income projections, FIA/MYGA comparison, recommendation',
            stage_order: 30,
            stage_color: 'var(--stage-suit)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            stage_name: 'Suitability',
            stage_description: 'Product suitability verified, CAF signed, BI written and unique',
            stage_order: 40,
            stage_color: 'var(--stage-qc)',
            gate_enforced: true,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            stage_name: 'IMO Review',
            stage_description: 'Gradient review and compliance docs verification',
            stage_order: 50,
            stage_color: 'var(--stage-ready)',
            gate_enforced: true,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            stage_name: 'Submitted',
            stage_description: 'Carrier underwriting and NIGO tracking',
            stage_order: 60,
            stage_color: 'var(--stage-submitted)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'funded',
            stage_name: 'Funded',
            stage_description: 'Account funded, commission tracking, client notified',
            stage_order: 70,
            stage_color: 'var(--stage-funded)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
    ],
    workflows: [
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            workflow_name: 'New Workflow',
            workflow_description: 'Initial case setup tasks',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            workflow_name: 'Intake Workflow',
            workflow_description: 'Statement collection and meeting scheduling',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            workflow_name: 'Analysis Workflow',
            workflow_description: 'Income projections and product comparison',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            workflow_name: 'Suitability Workflow',
            workflow_description: 'Product suitability and BI verification',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            workflow_name: 'IMO Review Workflow',
            workflow_description: 'Gradient compliance review',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            workflow_name: 'Submitted Workflow',
            workflow_description: 'Carrier underwriting and NIGO resolution',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            workflow_name: 'Funded Workflow',
            workflow_description: 'Funding confirmation and case closure',
            status: 'active',
        },
    ],
    steps: [
        // --- New ---
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'case_setup',
            step_name: 'Case Setup',
            step_description: 'Assign advisor and create client folder',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Intake ---
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'data_collection',
            step_name: 'Data Collection',
            step_description: 'Pull current statements and collect client data',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'meeting_setup',
            step_name: 'Meeting Setup',
            step_description: 'Schedule client meeting and prepare materials',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Analysis ---
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'income_projection',
            step_name: 'Income Projections',
            step_description: 'Run income projections for client retirement needs',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'product_comparison',
            step_name: 'Product Comparison',
            step_description: 'Compare FIA/MYGA options and build recommendation',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'recommendation',
            step_name: 'Build Recommendation',
            step_description: 'Build the formal annuity recommendation',
            step_order: 30,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Suitability ---
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'product_suitability',
            step_name: 'Product Suitability',
            step_description: 'Verify product suitability for client',
            step_order: 10,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'documentation',
            step_name: 'Documentation',
            step_description: 'CAF signing and Best Interest rationale',
            step_order: 20,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        // --- IMO Review ---
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'gradient_review',
            step_name: 'Gradient Review',
            step_description: 'Submit to Gradient for compliance review',
            step_order: 10,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'compliance_docs',
            step_name: 'Compliance Docs',
            step_description: 'Verify all compliance documentation',
            step_order: 20,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Submitted ---
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            step_id: 'carrier_underwriting',
            step_name: 'Carrier Underwriting',
            step_description: 'Track carrier underwriting process',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            step_id: 'nigo_resolution',
            step_name: 'NIGO Resolution',
            step_description: 'Resolve any Not-In-Good-Order items',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Funded ---
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'funding_confirmation',
            step_name: 'Funding Confirmation',
            step_description: 'Confirm funding and close case',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'close_case',
            step_name: 'Close Case',
            step_description: 'Commission tracking and client notification',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // Additional steps
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'initial_review',
            step_name: 'Initial Review',
            step_description: 'Review incoming case details',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'bi_verification',
            step_name: 'BI Verification',
            step_description: 'Best Interest rationale verification',
            step_order: 30,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'final_clearance',
            step_name: 'Final Clearance',
            step_description: 'Final clearance from Gradient for submission',
            step_order: 30,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
    ],
    tasks: [
        // =====================================================================
        // STAGE: New / Step: case_setup
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'case_setup',
            task_id: 'assign_advisor',
            task_name: 'Assign advisor',
            task_description: 'Assign the primary advisor to this annuity case',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'case_setup',
            task_id: 'create_folder',
            task_name: 'Create client folder in Drive',
            task_description: 'Create the client document folder in Google Drive',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- New / initial_review ---
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'initial_review',
            task_id: 'review_case_details',
            task_name: 'Review incoming case details',
            task_description: 'Review the initial case information and client needs',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Intake / Step: data_collection
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'data_collection',
            task_id: 'pull_current_statements',
            task_name: 'Pull current annuity statements',
            task_description: 'Retrieve current annuity statements from carriers',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'data_collection',
            task_id: 'collect_client_data',
            task_name: 'Collect client financial data',
            task_description: 'Collect income, expenses, and financial profile data',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'data_collection',
            task_id: 'id_collected',
            task_name: 'Government ID collected',
            task_description: 'Collect government-issued photo ID',
            task_order: 30,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Intake / meeting_setup ---
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'meeting_setup',
            task_id: 'schedule_meeting',
            task_name: 'Schedule client meeting',
            task_description: 'Schedule the annuity review meeting',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'meeting_setup',
            task_id: 'prepare_materials',
            task_name: 'Prepare meeting materials',
            task_description: 'Prepare current annuity summaries for review',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Analysis / Step: income_projection
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'income_projection',
            task_id: 'run_projections',
            task_name: 'Run income projections',
            task_description: 'Run retirement income projections based on client data',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'income_projection',
            task_id: 'review_projections',
            task_name: 'Review projection results',
            task_description: 'Review and document income projection findings',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Analysis / product_comparison ---
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'product_comparison',
            task_id: 'compare_fia_options',
            task_name: 'Compare FIA options',
            task_description: 'Compare Fixed Index Annuity options across carriers',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'product_comparison',
            task_id: 'compare_myga_options',
            task_name: 'Compare MYGA options',
            task_description: 'Compare Multi-Year Guaranteed Annuity options across carriers',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Analysis / recommendation ---
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'recommendation',
            task_id: 'build_recommendation',
            task_name: 'Build annuity recommendation',
            task_description: 'Build the formal annuity recommendation for client',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'recommendation',
            task_id: 'client_review_rec',
            task_name: 'Client reviews recommendation',
            task_description: 'Present recommendation to client and document feedback',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Suitability / Step: product_suitability
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'product_suitability',
            task_id: 'suitability_verified',
            task_name: 'Product suitability verified',
            task_description: 'Verify the annuity product is suitable for the client',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'product_suitability',
            task_id: 'surrender_review',
            task_name: 'Surrender charges reviewed',
            task_description: 'Review any surrender charges on existing contracts',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'product_suitability',
            task_id: 'lnw_limit_check',
            task_name: 'Liquid net worth within limits',
            task_description: 'System check: liquid net worth is within acceptable limits',
            task_order: 30,
            is_required: true,
            is_system_check: true,
            check_type: 'LNW_LIMIT',
            check_config: '{}',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Suitability / documentation ---
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'documentation',
            task_id: 'caf_signed',
            task_name: 'Client Assessment Form signed',
            task_description: 'CAF has been signed by the client',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'documentation',
            task_id: 'bi_written',
            task_name: 'Best Interest rationale written',
            task_description: 'Best Interest rationale has been written for this case',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Suitability / bi_verification ---
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'bi_verification',
            task_id: 'bi_unique',
            task_name: 'BI rationale is unique',
            task_description: 'System check: BI rationale is not copy-pasted from prior cases',
            task_order: 10,
            is_required: true,
            is_system_check: true,
            check_type: 'BI_UNIQUE',
            check_config: '{}',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'suitability',
            workflow_key: 'suitability_workflow',
            step_id: 'bi_verification',
            task_id: 'exchange_1035_disclosed',
            task_name: '1035 exchange disclosed (if applicable)',
            task_description: 'If 1035 exchange, ensure proper disclosure is documented',
            task_order: 20,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: IMO Review / Step: gradient_review
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'gradient_review',
            task_id: 'submit_to_gradient',
            task_name: 'Submit to Gradient for review',
            task_description: 'Submit the case to Gradient IMO for compliance review',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'gradient_review',
            task_id: 'gradient_feedback_received',
            task_name: 'Gradient feedback received',
            task_description: 'Received feedback from Gradient review team',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- IMO Review / compliance_docs ---
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'compliance_docs',
            task_id: 'compliance_docs_verified',
            task_name: 'Compliance docs verified',
            task_description: 'All required compliance documents have been verified',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'compliance_docs',
            task_id: 'corrections_applied',
            task_name: 'Corrections applied (if any)',
            task_description: 'Any corrections from Gradient review have been applied',
            task_order: 20,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- IMO Review / final_clearance ---
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'final_clearance',
            task_id: 'gradient_approved',
            task_name: 'Gradient final approval',
            task_description: 'Gradient has given final approval for carrier submission',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'imo_review',
            workflow_key: 'imo_review_workflow',
            step_id: 'final_clearance',
            task_id: 'ready_for_carrier',
            task_name: 'Ready for carrier submission',
            task_description: 'Case is cleared for carrier submission after Gradient approval',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Submitted / Step: carrier_underwriting
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            step_id: 'carrier_underwriting',
            task_id: 'submitted_to_carrier',
            task_name: 'Submitted to carrier',
            task_description: 'Application submitted to the annuity carrier',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            step_id: 'carrier_underwriting',
            task_id: 'confirmation_received',
            task_name: 'Carrier confirmation received',
            task_description: 'Received confirmation from carrier that application is being processed',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Submitted / nigo_resolution ---
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            step_id: 'nigo_resolution',
            task_id: 'nigo_items_resolved',
            task_name: 'NIGO items resolved (if any)',
            task_description: 'Any Not-In-Good-Order items have been resolved',
            task_order: 10,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'submitted',
            workflow_key: 'submitted_workflow',
            step_id: 'nigo_resolution',
            task_id: 'resubmission_confirmed',
            task_name: 'Resubmission confirmed (if NIGO)',
            task_description: 'If NIGO, confirm corrected documents have been resubmitted',
            task_order: 20,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Funded / Step: funding_confirmation
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'funding_confirmation',
            task_id: 'funding_confirmed',
            task_name: 'Funding confirmed',
            task_description: 'Account funding has been confirmed by the carrier',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'funding_confirmation',
            task_id: 'contract_received',
            task_name: 'Contract received',
            task_description: 'Annuity contract has been received from the carrier',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Funded / close_case ---
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'close_case',
            task_id: 'commission_tracked',
            task_name: 'Commission tracked',
            task_description: 'Commission verified and tracked in the system',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'close_case',
            task_id: 'client_notified',
            task_name: 'Client notified',
            task_description: 'Client has been notified of successful funding',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'funded',
            workflow_key: 'funded_workflow',
            step_id: 'close_case',
            task_id: 'records_updated',
            task_name: 'Records updated in ProDashX',
            task_description: 'Client records updated with new annuity information',
            task_order: 30,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
    ],
};
