/**
 * NBX_MEDICARE_MEDSUP pipeline config — Medicare Supplement / Ancillary.
 * 4 stages, 4 workflows, 4 steps, 11 task templates, no gated stages.
 * Simple pipeline: carrier-specific portal enrollment flow.
 */
import type {
  FlowPipelineDef,
  FlowStageDef,
  FlowWorkflowDef,
  FlowStepDef,
  FlowTaskTemplateDef,
} from '../types'

const PK = 'NBX_MEDICARE_MEDSUP'
const now = new Date().toISOString()

export const NBX_MEDICARE_MEDSUP_CONFIG = {
  pipeline: {
    pipeline_key: PK,
    pipeline_name: 'NBX - Medicare Supplement / Ancillary',
    description: 'New business processing for Med Supp and ancillary enrollments (carrier-specific portals)',
    portal: 'PRODASHX',
    domain: 'MEDICARE',
    default_view: 'KANBAN',
    icon: 'medical_services',
    status: 'active',
    created_at: now,
    updated_at: now,
  } as FlowPipelineDef,

  stages: [
    {
      pipeline_key: PK,
      stage_id: 'submission',
      stage_name: 'Submission',
      stage_description: 'Enrollment submitted via carrier-specific portal',
      stage_order: 10,
      stage_color: 'var(--stage-new)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'pending',
      stage_name: 'Pending',
      stage_description: 'Awaiting carrier decision, decline/correction handling',
      stage_order: 20,
      stage_color: 'var(--stage-intake)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'issued',
      stage_name: 'Issued',
      stage_description: 'Policy issued, confirmation sent',
      stage_order: 30,
      stage_color: 'var(--stage-submitted)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'cleanup',
      stage_name: 'Cleanup',
      stage_description: 'Cancel old policy, update records',
      stage_order: 40,
      stage_color: 'var(--stage-funded)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
  ] as FlowStageDef[],

  workflows: [
    {
      pipeline_key: PK,
      stage_id: 'submission',
      workflow_key: 'submission_workflow',
      workflow_name: 'Submission Workflow',
      workflow_description: 'Carrier enrollment submission tasks',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'pending',
      workflow_key: 'pending_workflow',
      workflow_name: 'Pending Workflow',
      workflow_description: 'Pending decision and correction tasks',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'issued',
      workflow_key: 'issued_workflow',
      workflow_name: 'Issued Workflow',
      workflow_description: 'Policy issuance and confirmation tasks',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'cleanup',
      workflow_key: 'cleanup_workflow',
      workflow_name: 'Cleanup Workflow',
      workflow_description: 'Old policy cancellation and record updates',
      status: 'active',
    },
  ] as FlowWorkflowDef[],

  steps: [
    {
      pipeline_key: PK,
      stage_id: 'submission',
      workflow_key: 'submission_workflow',
      step_id: 'enrollment_submit',
      step_name: 'Enrollment Submission',
      step_description: 'Submit enrollment via carrier portal',
      step_order: 10,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'pending',
      workflow_key: 'pending_workflow',
      step_id: 'pending_review',
      step_name: 'Pending Review',
      step_description: 'Monitor carrier decision and handle corrections',
      step_order: 10,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'issued',
      workflow_key: 'issued_workflow',
      step_id: 'issuance_confirm',
      step_name: 'Issuance Confirmation',
      step_description: 'Confirm policy issuance and notify client',
      step_order: 10,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'cleanup',
      workflow_key: 'cleanup_workflow',
      step_id: 'record_cleanup',
      step_name: 'Record Cleanup',
      step_description: 'Cancel old policy and update system records',
      step_order: 10,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
  ] as FlowStepDef[],

  tasks: [
    // =====================================================================
    // STAGE: Submission / Step: enrollment_submit (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'submission',
      workflow_key: 'submission_workflow',
      step_id: 'enrollment_submit',
      task_id: 'enrollment_submitted',
      task_name: 'Enrollment submitted to carrier',
      task_description: 'Med Supp enrollment submitted via carrier-specific portal',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'submission',
      workflow_key: 'submission_workflow',
      step_id: 'enrollment_submit',
      task_id: 'confirmation_number',
      task_name: 'Confirmation number recorded',
      task_description: 'Record the carrier confirmation number for tracking',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'submission',
      workflow_key: 'submission_workflow',
      step_id: 'enrollment_submit',
      task_id: 'payment_method_confirmed',
      task_name: 'Payment method confirmed',
      task_description: 'Client payment method has been set up and confirmed',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Pending / Step: pending_review (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'pending',
      workflow_key: 'pending_workflow',
      step_id: 'pending_review',
      task_id: 'carrier_status_checked',
      task_name: 'Carrier status checked',
      task_description: 'Check carrier portal for enrollment status',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'pending',
      workflow_key: 'pending_workflow',
      step_id: 'pending_review',
      task_id: 'corrections_submitted',
      task_name: 'Corrections submitted (if needed)',
      task_description: 'Submit any required corrections to the carrier',
      task_order: 20,
      is_required: false,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'pending',
      workflow_key: 'pending_workflow',
      step_id: 'pending_review',
      task_id: 'decline_handled',
      task_name: 'Decline handled (if applicable)',
      task_description: 'If declined, document reason and determine next steps',
      task_order: 30,
      is_required: false,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Issued / Step: issuance_confirm (2 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'issued',
      workflow_key: 'issued_workflow',
      step_id: 'issuance_confirm',
      task_id: 'policy_issued',
      task_name: 'Policy issued',
      task_description: 'Med Supp policy has been issued by the carrier',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'issued',
      workflow_key: 'issued_workflow',
      step_id: 'issuance_confirm',
      task_id: 'client_notified',
      task_name: 'Client notified of issuance',
      task_description: 'Client has been notified their policy is issued',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Cleanup / Step: record_cleanup (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'cleanup',
      workflow_key: 'cleanup_workflow',
      step_id: 'record_cleanup',
      task_id: 'cancel_old_policy',
      task_name: 'Cancel old policy',
      task_description: 'Cancel the prior Med Supp policy (if replacing)',
      task_order: 10,
      is_required: false,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'cleanup',
      workflow_key: 'cleanup_workflow',
      step_id: 'record_cleanup',
      task_id: 'records_updated',
      task_name: 'Records updated in ProDashX',
      task_description: 'Client records updated with new policy information',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'cleanup',
      workflow_key: 'cleanup_workflow',
      step_id: 'record_cleanup',
      task_id: 'commission_tracked',
      task_name: 'Commission tracked',
      task_description: 'Commission verified and tracked in the system',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
  ] as FlowTaskTemplateDef[],
}
