"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NBX_LIFE_CONFIG = void 0;
const PK = 'NBX_LIFE';
const now = new Date().toISOString();
exports.NBX_LIFE_CONFIG = {
    pipeline: {
        pipeline_key: PK,
        pipeline_name: 'NBX - Life Insurance',
        description: 'New business processing for life insurance applications',
        portal: 'PRODASHX',
        domain: 'LIFE',
        default_view: 'KANBAN',
        icon: 'health_and_safety',
        status: 'active',
        created_at: now,
        updated_at: now,
    },
    stages: [
        {
            pipeline_key: PK,
            stage_id: 'new',
            stage_name: 'New',
            stage_description: 'New life insurance case intake',
            stage_order: 10,
            stage_color: 'var(--stage-new)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            stage_name: 'Intake',
            stage_description: 'Collect current policy data, statements, and schedule meeting',
            stage_order: 20,
            stage_color: 'var(--stage-intake)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            stage_name: 'Analysis',
            stage_description: 'IFI analysis, carrier comparison, recommendation building',
            stage_order: 30,
            stage_color: 'var(--stage-suit)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            stage_name: 'Application',
            stage_description: 'Application completion, medical requirements, and suitability verification',
            stage_order: 40,
            stage_color: 'var(--stage-qc)',
            gate_enforced: true,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            stage_name: 'Underwriting',
            stage_description: 'Track APS forms, monitor underwriting, handle counter-offers',
            stage_order: 50,
            stage_color: 'var(--stage-ready)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'issued',
            stage_name: 'Issued',
            stage_description: 'Policy issued, delivery receipt, commission tracking',
            stage_order: 60,
            stage_color: 'var(--stage-submitted)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            stage_name: 'Declined/Re-Shop',
            stage_description: 'Carrier decline handling and alternative carrier search',
            stage_order: 70,
            stage_color: 'var(--stage-funded)',
            gate_enforced: false,
            has_workflow: true,
            ghl_stage_id: '',
            status: 'active',
        },
    ],
    workflows: [
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            workflow_name: 'New Workflow',
            workflow_description: 'Initial case setup tasks',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            workflow_name: 'Intake Workflow',
            workflow_description: 'Policy collection and meeting scheduling',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            workflow_name: 'Analysis Workflow',
            workflow_description: 'IFI analysis and carrier comparison',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            workflow_name: 'Application Workflow',
            workflow_description: 'Application completion and suitability checks',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            workflow_name: 'Underwriting Workflow',
            workflow_description: 'Underwriting tracking and counter-offer handling',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            workflow_name: 'Issued Workflow',
            workflow_description: 'Policy delivery and commission tracking',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            workflow_name: 'Declined/Re-Shop Workflow',
            workflow_description: 'Decline handling and alternative carrier search',
            status: 'active',
        },
    ],
    steps: [
        // --- New ---
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'case_setup',
            step_name: 'Case Setup',
            step_description: 'Assign advisor and create client folder',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Intake ---
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'policy_collection',
            step_name: 'Policy Collection',
            step_description: 'Pull current policies and collect statements',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'meeting_prep',
            step_name: 'Meeting Prep',
            step_description: 'Schedule and prepare for client meeting',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Analysis ---
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'ifi_analysis',
            step_name: 'IFI Analysis',
            step_description: 'Run in-force illustration analysis',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'carrier_comparison',
            step_name: 'Carrier Comparison',
            step_description: 'Compare carrier options and build recommendation',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Application ---
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'app_completion',
            step_name: 'Application Completion',
            step_description: 'Complete the carrier application',
            step_order: 10,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'medical_reqs',
            step_name: 'Medical Requirements',
            step_description: 'Order and track medical requirements',
            step_order: 20,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'suitability_verify',
            step_name: 'Suitability Verification',
            step_description: 'Verify product suitability for client',
            step_order: 30,
            gate_enforced: true,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Underwriting ---
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_tracking',
            step_name: 'Underwriting Tracking',
            step_description: 'Track APS forms and underwriting status',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'counter_offer',
            step_name: 'Counter-Offer Handling',
            step_description: 'Handle any carrier counter-offers',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Issued ---
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'policy_delivery',
            step_name: 'Policy Delivery',
            step_description: 'Policy delivery and receipt confirmation',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'commission_tracking',
            step_name: 'Commission Tracking',
            step_description: 'Track commission and close case',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Declined/Re-Shop ---
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            step_id: 'decline_handling',
            step_name: 'Decline Handling',
            step_description: 'Process carrier decline and evaluate options',
            step_order: 10,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            step_id: 'alternative_search',
            step_name: 'Alternative Carrier Search',
            step_description: 'Search for alternative carriers',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        // --- Additional steps for depth ---
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'initial_review',
            step_name: 'Initial Review',
            step_description: 'Review incoming case details',
            step_order: 20,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_decision',
            step_name: 'Underwriting Decision',
            step_description: 'Process underwriting decision',
            step_order: 30,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'recommendation',
            step_name: 'Build Recommendation',
            step_description: 'Build life insurance recommendation for client',
            step_order: 30,
            gate_enforced: false,
            execution_type: 'manual',
            status: 'active',
        },
    ],
    tasks: [
        // =====================================================================
        // STAGE: New / Step: case_setup
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'case_setup',
            task_id: 'assign_advisor',
            task_name: 'Assign advisor',
            task_description: 'Assign the primary advisor to this life case',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'case_setup',
            task_id: 'create_folder',
            task_name: 'Create client folder in Drive',
            task_description: 'Create the client document folder in Google Drive',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- New / initial_review ---
        {
            pipeline_key: PK,
            stage_id: 'new',
            workflow_key: 'new_workflow',
            step_id: 'initial_review',
            task_id: 'review_case_details',
            task_name: 'Review incoming case details',
            task_description: 'Review the initial case information and client needs',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Intake / Step: policy_collection
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'policy_collection',
            task_id: 'pull_current_policies',
            task_name: 'Pull current life policy details',
            task_description: 'Retrieve current life insurance policy details from carriers',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'policy_collection',
            task_id: 'collect_statements',
            task_name: 'Collect most recent statements',
            task_description: 'Collect the most recent policy statements from the client',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'policy_collection',
            task_id: 'health_history_gathered',
            task_name: 'Gather health history',
            task_description: 'Collect relevant health history information from client',
            task_order: 30,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Intake / meeting_prep ---
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'meeting_prep',
            task_id: 'schedule_meeting',
            task_name: 'Schedule client meeting',
            task_description: 'Schedule the initial life insurance review meeting',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'intake',
            workflow_key: 'intake_workflow',
            step_id: 'meeting_prep',
            task_id: 'prepare_materials',
            task_name: 'Prepare meeting materials',
            task_description: 'Prepare policy summaries and comparison materials',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Analysis / Step: ifi_analysis
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'ifi_analysis',
            task_id: 'run_ifi',
            task_name: 'Run IFI analysis',
            task_description: 'Run in-force illustration analysis on current policies',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'ifi_analysis',
            task_id: 'review_ifi_results',
            task_name: 'Review IFI results',
            task_description: 'Review and document IFI analysis findings',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Analysis / carrier_comparison ---
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'carrier_comparison',
            task_id: 'compare_carriers',
            task_name: 'Compare carrier options',
            task_description: 'Compare available carrier options for the client',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'carrier_comparison',
            task_id: 'document_comparison',
            task_name: 'Document carrier comparison',
            task_description: 'Document the carrier comparison analysis for the file',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Analysis / recommendation ---
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'recommendation',
            task_id: 'build_recommendation',
            task_name: 'Build life recommendation',
            task_description: 'Build the formal life insurance recommendation',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'analysis',
            workflow_key: 'analysis_workflow',
            step_id: 'recommendation',
            task_id: 'client_review_rec',
            task_name: 'Client reviews recommendation',
            task_description: 'Present recommendation to client and document feedback',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Application / Step: app_completion
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'app_completion',
            task_id: 'complete_application',
            task_name: 'Complete carrier application',
            task_description: 'Complete the insurance application with all required fields',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'app_completion',
            task_id: 'beneficiary_designation',
            task_name: 'Beneficiary designation completed',
            task_description: 'Confirm beneficiary designations are properly documented',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'app_completion',
            task_id: 'hipaa_auth_signed',
            task_name: 'HIPAA authorization signed',
            task_description: 'HIPAA authorization form signed by client',
            task_order: 30,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Application / medical_reqs ---
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'medical_reqs',
            task_id: 'medical_ordered',
            task_name: 'Medical requirements ordered',
            task_description: 'Order required medical exams and labs',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'medical_reqs',
            task_id: 'medical_completed',
            task_name: 'Medical requirements completed',
            task_description: 'All medical exams and labs have been completed',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Application / suitability_verify ---
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'suitability_verify',
            task_id: 'suitability_verified',
            task_name: 'Suitability verified',
            task_description: 'Product suitability has been verified for the client',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'application',
            workflow_key: 'application_workflow',
            step_id: 'suitability_verify',
            task_id: 'replacement_disclosure',
            task_name: 'Replacement disclosure completed',
            task_description: 'If replacing existing policy, complete replacement disclosure forms',
            task_order: 20,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Underwriting / Step: uw_tracking
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_tracking',
            task_id: 'aps_ordered',
            task_name: 'APS forms ordered',
            task_description: 'Attending Physician Statements have been ordered',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_tracking',
            task_id: 'aps_received',
            task_name: 'APS forms received',
            task_description: 'All APS forms have been received by the carrier',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_tracking',
            task_id: 'uw_status_monitored',
            task_name: 'Monitor underwriting status',
            task_description: 'Check in on underwriting status regularly',
            task_order: 30,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Underwriting / counter_offer ---
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'counter_offer',
            task_id: 'review_counter_offer',
            task_name: 'Review counter-offer (if any)',
            task_description: 'Review and evaluate any counter-offers from the carrier',
            task_order: 10,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'counter_offer',
            task_id: 'client_decision',
            task_name: 'Client decision on counter-offer',
            task_description: 'Obtain client decision on any counter-offer',
            task_order: 20,
            is_required: false,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Underwriting / uw_decision ---
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_decision',
            task_id: 'uw_decision_received',
            task_name: 'Underwriting decision received',
            task_description: 'Final underwriting decision has been received from carrier',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'underwriting',
            workflow_key: 'underwriting_workflow',
            step_id: 'uw_decision',
            task_id: 'notify_client_decision',
            task_name: 'Notify client of decision',
            task_description: 'Inform client of the underwriting decision',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Issued / Step: policy_delivery
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'policy_delivery',
            task_id: 'policy_issued',
            task_name: 'Policy issued by carrier',
            task_description: 'Carrier has issued the policy',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'policy_delivery',
            task_id: 'delivery_receipt',
            task_name: 'Delivery receipt signed',
            task_description: 'Client has signed the policy delivery receipt',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'policy_delivery',
            task_id: 'client_notified',
            task_name: 'Client notified of issuance',
            task_description: 'Client has been notified their policy is issued',
            task_order: 30,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Issued / commission_tracking ---
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'commission_tracking',
            task_id: 'commission_verified',
            task_name: 'Commission verified',
            task_description: 'Commission amount verified against carrier statement',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'issued',
            workflow_key: 'issued_workflow',
            step_id: 'commission_tracking',
            task_id: 'records_updated',
            task_name: 'Records updated in ProDashX',
            task_description: 'Client records updated with new policy information',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // =====================================================================
        // STAGE: Declined/Re-Shop / Step: decline_handling
        // =====================================================================
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            step_id: 'decline_handling',
            task_id: 'document_decline_reason',
            task_name: 'Document decline reason',
            task_description: 'Document the carrier decline reason for the file',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            step_id: 'decline_handling',
            task_id: 'notify_client_decline',
            task_name: 'Notify client of decline',
            task_description: 'Inform client of the carrier decline and next steps',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        // --- Declined/Re-Shop / alternative_search ---
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            step_id: 'alternative_search',
            task_id: 'search_alternative_carriers',
            task_name: 'Search alternative carriers',
            task_description: 'Research alternative carriers that may accept the risk',
            task_order: 10,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
        {
            pipeline_key: PK,
            stage_id: 'declined_reshop',
            workflow_key: 'declined_reshop_workflow',
            step_id: 'alternative_search',
            task_id: 'present_alternatives',
            task_name: 'Present alternatives to client',
            task_description: 'Present alternative carrier options to the client',
            task_order: 20,
            is_required: true,
            is_system_check: false,
            check_type: 'MANUAL',
            default_owner: 'ADVISOR',
            role_applicability: '',
            status: 'active',
        },
    ],
};
