/**
 * NBX_INVESTMENTS pipeline config — Investments (Gradient).
 * Ported from archive/RAPID_FLOW/FLOW_DevTools.gs _seedNBXSecurities().
 * 7 stages, 7 workflows, 14 steps, 40 task templates, 3 gated stages.
 */
import type {
  FlowPipelineDef,
  FlowStageDef,
  FlowWorkflowDef,
  FlowStepDef,
  FlowTaskTemplateDef,
} from '../types'

const PK = 'NBX_INVESTMENTS'
const now = new Date().toISOString()

export const NBX_INVESTMENTS_CONFIG = {
  pipeline: {
    pipeline_key: PK,
    pipeline_name: 'NBX - Investments',
    description: 'New business processing for investment accounts (Gradient)',
    portal: 'PRODASHX',
    domain: 'INVESTMENTS',
    platform_carrier: 'GS_GWM_GI',
    product_type: 'TAMP',
    default_view: 'KANBAN',
    icon: 'account_balance',
    status: 'active',
    created_at: now,
    updated_at: now,
  } as FlowPipelineDef,

  stages: [
    {
      pipeline_key: PK,
      stage_id: 'new',
      stage_name: 'New',
      stage_description: 'New case intake',
      stage_order: 10,
      stage_color: 'var(--stage-new)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      stage_name: 'Intake',
      stage_description: 'Document collection and client introduction',
      stage_order: 20,
      stage_color: 'var(--stage-intake)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      stage_name: 'Suitability',
      stage_description: 'Client profile verification and product suitability assessment',
      stage_order: 30,
      stage_color: 'var(--stage-suit)',
      gate_enforced: true,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      stage_name: 'QC Review',
      stage_description: 'Quality control review of all documents and data',
      stage_order: 40,
      stage_color: 'var(--stage-qc)',
      gate_enforced: true,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      stage_name: 'Ready to Submit',
      stage_description: 'Final preparation and DocuSign for submission',
      stage_order: 50,
      stage_color: 'var(--stage-ready)',
      gate_enforced: true,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'submitted',
      stage_name: 'Submitted',
      stage_description: 'Submitted to custodian/carrier, awaiting confirmation',
      stage_order: 60,
      stage_color: 'var(--stage-submitted)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'funded',
      stage_name: 'Funded',
      stage_description: 'Account funded, case closed',
      stage_order: 70,
      stage_color: 'var(--stage-funded)',
      gate_enforced: false,
      has_workflow: true,
      ghl_stage_id: '',
      status: 'active',
    },
  ] as FlowStageDef[],

  workflows: [
    {
      pipeline_key: PK,
      stage_id: 'new',
      workflow_key: 'new_workflow',
      workflow_name: 'New Workflow',
      workflow_description: 'Initial case setup tasks',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      workflow_name: 'Intake Workflow',
      workflow_description: 'Document gathering and client introduction',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      workflow_name: 'Suitability Workflow',
      workflow_description: 'Client profile and product suitability verification',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      workflow_name: 'QC Review Workflow',
      workflow_description: 'Quality control and compliance review',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      workflow_name: 'Ready to Submit Workflow',
      workflow_description: 'Final submission preparation with DEX integration',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'submitted',
      workflow_key: 'submitted_workflow',
      workflow_name: 'Submitted Workflow',
      workflow_description: 'Track carrier submission and confirmations',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'funded',
      workflow_key: 'funded_workflow',
      workflow_name: 'Funded Workflow',
      workflow_description: 'Case closure and client notification',
      status: 'active',
    },
  ] as FlowWorkflowDef[],

  steps: [
    // --- New ---
    {
      pipeline_key: PK,
      stage_id: 'new',
      workflow_key: 'new_workflow',
      step_id: 'case_setup',
      step_name: 'Case Setup',
      step_description: 'Initial case creation and advisor assignment',
      step_order: 10,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    // --- Intake ---
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'gather_docs',
      step_name: 'Gather Documents',
      step_description: 'Collect client statements and identification',
      step_order: 10,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'client_intro',
      step_name: 'Client Introduction',
      step_description: 'Introduction meeting and risk profiling',
      step_order: 20,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
    // --- Suitability ---
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'client_profile',
      step_name: 'Client Profile',
      step_description: 'Verify client financial profile fields',
      step_order: 10,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'product_suitability',
      step_name: 'Product Suitability',
      step_description: 'Validate product-level suitability requirements',
      step_order: 20,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'documentation',
      step_name: 'Documentation',
      step_description: 'CAF signing and Best Interest rationale',
      step_order: 30,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    // --- QC Review ---
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'document_integrity',
      step_name: 'Document Integrity',
      step_description: 'Verify all forms present and properly signed',
      step_order: 10,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'data_completeness',
      step_name: 'Data Completeness',
      step_description: 'Cross-form data consistency checks',
      step_order: 20,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'compliance_checks',
      step_name: 'Compliance Checks',
      step_description: 'Custodian verification and Signal/legacy checks',
      step_order: 30,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'final_approval',
      step_name: 'Final Approval',
      step_description: 'QC pass and submission readiness confirmation',
      step_order: 40,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    // --- Ready to Submit ---
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'submission_prep',
      step_name: 'Submission Prep',
      step_description: 'Generate DEX form kit and DocuSign envelope',
      step_order: 10,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'final_verify',
      step_name: 'Final Verify',
      step_description: 'Confirm all documents signed and package ready',
      step_order: 20,
      gate_enforced: true,
      execution_type: 'manual',
      status: 'active',
    },
    // --- Submitted ---
    {
      pipeline_key: PK,
      stage_id: 'submitted',
      workflow_key: 'submitted_workflow',
      step_id: 'track_submission',
      step_name: 'Track Submission',
      step_description: 'Monitor carrier submission and resolve NIGO items',
      step_order: 10,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
    // --- Funded ---
    {
      pipeline_key: PK,
      stage_id: 'funded',
      workflow_key: 'funded_workflow',
      step_id: 'close_case',
      step_name: 'Close Case',
      step_description: 'Confirm funding, notify client, link account',
      step_order: 10,
      gate_enforced: false,
      execution_type: 'manual',
      status: 'active',
    },
  ] as FlowStepDef[],

  tasks: [
    // =====================================================================
    // STAGE: New / Step: case_setup (2 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'new',
      workflow_key: 'new_workflow',
      step_id: 'case_setup',
      task_id: 'assign_advisor',
      task_name: 'Assign advisor',
      task_description: 'Assign the primary advisor to this case',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'new',
      workflow_key: 'new_workflow',
      step_id: 'case_setup',
      task_id: 'create_folder',
      task_name: 'Create client folder in Drive',
      task_description: 'Create the client document folder in Google Drive',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Intake / Step: gather_docs (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'gather_docs',
      task_id: 'statement_collected',
      task_name: 'Most recent statement collected',
      task_description: 'Collect the most recent account statement from the client',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'gather_docs',
      task_id: 'id_collected',
      task_name: 'Government ID collected',
      task_description: 'Collect government-issued photo ID',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'gather_docs',
      task_id: 'existing_forms_scanned',
      task_name: 'Existing carrier forms scanned',
      task_description: 'Scan any existing carrier forms into the client folder',
      task_order: 30,
      is_required: false,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Intake / Step: client_intro (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'client_intro',
      task_id: 'intro_meeting_held',
      task_name: 'Introduction meeting held',
      task_description: 'Conduct the initial client introduction meeting',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'client_intro',
      task_id: 'risk_profile_completed',
      task_name: 'Risk tolerance questionnaire done',
      task_description: 'Complete the risk tolerance assessment questionnaire',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'intake',
      workflow_key: 'intake_workflow',
      step_id: 'client_intro',
      task_id: 'goals_documented',
      task_name: 'Investment goals documented',
      task_description: 'Document the client investment goals and objectives',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Suitability / Step: client_profile (4 tasks - system checks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'client_profile',
      task_id: 'net_worth_present',
      task_name: 'Net worth on CAF',
      task_description: 'Verify net worth is present on Client Assessment Form',
      task_order: 10,
      is_required: true,
      is_system_check: true,
      check_type: 'FIELD_PRESENT',
      check_config: '{"field":"net_worth"}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'client_profile',
      task_id: 'income_present',
      task_name: 'Annual income documented',
      task_description: 'Verify annual income is documented',
      task_order: 20,
      is_required: true,
      is_system_check: true,
      check_type: 'FIELD_PRESENT',
      check_config: '{"field":"annual_income"}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'client_profile',
      task_id: 'risk_tolerance_present',
      task_name: 'Risk tolerance documented',
      task_description: 'Verify risk tolerance assessment is on file',
      task_order: 30,
      is_required: true,
      is_system_check: true,
      check_type: 'FIELD_PRESENT',
      check_config: '{"field":"risk_tolerance"}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'client_profile',
      task_id: 'investment_obj_present',
      task_name: 'Investment objective stated',
      task_description: 'Verify investment objective is stated on CAF',
      task_order: 40,
      is_required: true,
      is_system_check: true,
      check_type: 'FIELD_PRESENT',
      check_config: '{"field":"investment_objective"}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Suitability / Step: product_suitability (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'product_suitability',
      task_id: 'lnw_limit_check',
      task_name: 'Liquid net worth within limits',
      task_description: 'System check: liquid net worth is within acceptable limits',
      task_order: 10,
      is_required: true,
      is_system_check: true,
      check_type: 'LNW_LIMIT',
      check_config: '{}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'product_suitability',
      task_id: 'time_horizon_check',
      task_name: 'Time horizon appropriate',
      task_description: 'Verify client time horizon matches product requirements',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'product_suitability',
      task_id: 'product_understanding',
      task_name: 'Client understands product',
      task_description: 'Confirm client understands the product features and risks',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Suitability / Step: documentation (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'documentation',
      task_id: 'caf_signed',
      task_name: 'Client Assessment Form signed',
      task_description: 'Client Assessment Form has been signed by the client',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'documentation',
      task_id: 'bi_written',
      task_name: 'Best Interest rationale written',
      task_description: 'Best Interest rationale has been written for this case',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'suitability',
      workflow_key: 'suitability_workflow',
      step_id: 'documentation',
      task_id: 'bi_unique',
      task_name: 'BI rationale is unique',
      task_description: 'System check: BI rationale is not copy-pasted from prior cases',
      task_order: 30,
      is_required: true,
      is_system_check: true,
      check_type: 'BI_UNIQUE',
      check_config: '{}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: QC Review / Step: document_integrity (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'document_integrity',
      task_id: 'all_forms_present',
      task_name: 'All required forms in folder',
      task_description: 'Verify all required forms are present in the client folder',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'document_integrity',
      task_id: 'signatures_verified',
      task_name: 'Signatures on all pages',
      task_description: 'Verify signatures are present on all required pages',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'document_integrity',
      task_id: 'no_blank_fields',
      task_name: 'No blank required fields',
      task_description: 'Verify no required fields are left blank on any form',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: QC Review / Step: data_completeness (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'data_completeness',
      task_id: 'name_match',
      task_name: 'Client name matches across forms',
      task_description: 'Verify client name is consistent across all documents',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'data_completeness',
      task_id: 'account_num_match',
      task_name: 'Account numbers consistent',
      task_description: 'Verify account numbers match across all forms',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'data_completeness',
      task_id: 'amounts_match',
      task_name: 'Dollar amounts match',
      task_description: 'Verify dollar amounts are consistent across forms',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: QC Review / Step: compliance_checks (3 tasks - includes system checks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'compliance_checks',
      task_id: 'correct_custodian',
      task_name: 'Correct custodian on forms',
      task_description: 'System check: forms reference Schwab (RIA) or RBC (BD) via Gradient',
      task_order: 10,
      is_required: true,
      is_system_check: true,
      check_type: 'CORRECT_CUSTODIAN',
      check_config: '{}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'compliance_checks',
      task_id: 'no_signal',
      task_name: 'No Signal Wealth references',
      task_description: 'System check: custodian field does not contain legacy Signal references',
      task_order: 20,
      is_required: true,
      is_system_check: true,
      check_type: 'FIELD_NOT_CONTAINS',
      check_config: '{"field":"custodian","forbidden":"Signal"}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'compliance_checks',
      task_id: 'suitability_approved',
      task_name: 'Suitability review approved',
      task_description: 'Confirm suitability review has been approved',
      task_order: 30,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: QC Review / Step: final_approval (2 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'final_approval',
      task_id: 'qc_pass',
      task_name: 'QC review passed',
      task_description: 'Quality control review has been passed',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'qc_review',
      workflow_key: 'qc_review_workflow',
      step_id: 'final_approval',
      task_id: 'ready_for_submission',
      task_name: 'Marked ready for submission',
      task_description: 'Case has been marked as ready for carrier submission',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Ready to Submit / Step: submission_prep (3 tasks - includes DEX)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'submission_prep',
      task_id: 'dex_kit_generated',
      task_name: 'DEX form kit generated',
      task_description: 'System check: DEX pipeline has generated the form kit',
      task_order: 10,
      is_required: true,
      is_system_check: true,
      check_type: 'DEX_KIT_GENERATE',
      check_config: '{}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'submission_prep',
      task_id: 'kit_reviewed',
      task_name: 'Form kit reviewed',
      task_description: 'The generated form kit has been reviewed for accuracy',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'submission_prep',
      task_id: 'docusign_sent',
      task_name: 'DocuSign sent for signing',
      task_description: 'System check: DocuSign envelope sent via DEX pipeline',
      task_order: 30,
      is_required: true,
      is_system_check: true,
      check_type: 'DEX_DOCUSIGN',
      check_config: '{}',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Ready to Submit / Step: final_verify (2 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'final_verify',
      task_id: 'all_signed',
      task_name: 'All documents signed',
      task_description: 'Confirm all documents have been signed via DocuSign',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'ready_to_submit',
      workflow_key: 'ready_to_submit_workflow',
      step_id: 'final_verify',
      task_id: 'submission_ready',
      task_name: 'Package ready to submit',
      task_description: 'Full submission package is assembled and ready',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Submitted / Step: track_submission (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'submitted',
      workflow_key: 'submitted_workflow',
      step_id: 'track_submission',
      task_id: 'submitted_to_carrier',
      task_name: 'Submitted to custodian/carrier',
      task_description: 'Package has been submitted to the custodian or carrier',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'submitted',
      workflow_key: 'submitted_workflow',
      step_id: 'track_submission',
      task_id: 'confirmation_received',
      task_name: 'Confirmation received',
      task_description: 'Carrier/custodian confirmation has been received',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'submitted',
      workflow_key: 'submitted_workflow',
      step_id: 'track_submission',
      task_id: 'nigo_resolved',
      task_name: 'NIGO items resolved (if any)',
      task_description: 'Any Not-In-Good-Order items have been resolved',
      task_order: 30,
      is_required: false,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    // =====================================================================
    // STAGE: Funded / Step: close_case (3 tasks)
    // =====================================================================
    {
      pipeline_key: PK,
      stage_id: 'funded',
      workflow_key: 'funded_workflow',
      step_id: 'close_case',
      task_id: 'funding_confirmed',
      task_name: 'Funding confirmed',
      task_description: 'Account funding has been confirmed by the custodian',
      task_order: 10,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'funded',
      workflow_key: 'funded_workflow',
      step_id: 'close_case',
      task_id: 'client_notified',
      task_name: 'Client notified',
      task_description: 'Client has been notified of successful funding',
      task_order: 20,
      is_required: true,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
    {
      pipeline_key: PK,
      stage_id: 'funded',
      workflow_key: 'funded_workflow',
      step_id: 'close_case',
      task_id: 'account_linked',
      task_name: 'Account linked in ProDashX',
      task_description: 'Account has been linked in ProDashX for ongoing management',
      task_order: 30,
      is_required: false,
      is_system_check: false,
      check_type: 'MANUAL',
      default_owner: 'ADVISOR',
      role_applicability: '',
      status: 'active',
    },
  ] as FlowTaskTemplateDef[],
}
