"use strict";
/**
 * PROSPECT_LEGACY pipeline config.
 * 7 stages: New Lead -> Engaged -> Connect 1/2/3 -> Outcome Yes/No
 * Mirrors PROSPECT_RETIREMENT structure exactly.
 * On "Outcome Yes" -> handoff to SALES_LEGACY.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROSPECT_LEGACY_CONFIG = void 0;
// ============================================================================
// Pipeline
// ============================================================================
const pipeline = {
    pipeline_key: 'PROSPECT_LEGACY',
    pipeline_name: 'Prospecting - Legacy',
    description: 'Legacy services prospecting pipeline. Mirrors Retirement prospecting. Hands off to Sales Process - Legacy.',
    portal: 'PRODASHX',
    domain: 'LEGACY',
    default_view: 'kanban',
    icon: 'person_search',
    handoff_pipeline: 'SALES_LEGACY',
    status: 'active',
    created_at: '2026-03-13T00:00:00.000Z',
    updated_at: '2026-03-13T00:00:00.000Z',
};
// ============================================================================
// Stages
// ============================================================================
const stages = [
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'new_lead',
        stage_name: 'New Lead',
        stage_description: 'New Legacy lead received. Initial qualification pending.',
        stage_order: 10,
        stage_color: 'gray',
        gate_enforced: false,
        has_workflow: true,
        ghl_stage_id: 'new_lead',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'engaged',
        stage_name: 'Engaged',
        stage_description: 'Lead is engaged. Initial contact made.',
        stage_order: 20,
        stage_color: 'blue',
        gate_enforced: false,
        has_workflow: true,
        ghl_stage_id: 'engaged',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_1',
        stage_name: 'Connect 1',
        stage_description: 'First connect attempt.',
        stage_order: 30,
        stage_color: 'cyan',
        gate_enforced: false,
        has_workflow: true,
        ghl_stage_id: 'connect_1',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_2',
        stage_name: 'Connect 2',
        stage_description: 'Second connect attempt.',
        stage_order: 40,
        stage_color: 'yellow',
        gate_enforced: false,
        has_workflow: true,
        ghl_stage_id: 'connect_2',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_3',
        stage_name: 'Connect 3',
        stage_description: 'Third connect attempt.',
        stage_order: 50,
        stage_color: 'orange',
        gate_enforced: false,
        has_workflow: true,
        ghl_stage_id: 'connect_3',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'outcome_yes',
        stage_name: 'Outcome Yes',
        stage_description: 'Prospect converted. Handoff to Sales Process - Legacy.',
        stage_order: 60,
        stage_color: 'green',
        gate_enforced: false,
        has_workflow: true,
        ghl_stage_id: 'outcome_yes',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'outcome_no',
        stage_name: 'Outcome No',
        stage_description: 'Prospect declined or unresponsive.',
        stage_order: 70,
        stage_color: 'red',
        gate_enforced: false,
        has_workflow: false,
        ghl_stage_id: 'outcome_no',
        status: 'active',
    },
];
// ============================================================================
// Workflows
// ============================================================================
const workflows = [
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'new_lead',
        workflow_key: 'new_lead_workflow',
        workflow_name: 'New Lead Workflow',
        workflow_description: 'Initial Legacy lead qualification.',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'engaged',
        workflow_key: 'engaged_workflow',
        workflow_name: 'Engaged Workflow',
        workflow_description: 'Initial engagement and contact.',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_1',
        workflow_key: 'connect_1_workflow',
        workflow_name: 'Connect 1 Workflow',
        workflow_description: 'First connect attempt.',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_2',
        workflow_key: 'connect_2_workflow',
        workflow_name: 'Connect 2 Workflow',
        workflow_description: 'Second connect attempt.',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_3',
        workflow_key: 'connect_3_workflow',
        workflow_name: 'Connect 3 Workflow',
        workflow_description: 'Third connect attempt.',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'outcome_yes',
        workflow_key: 'outcome_yes_workflow',
        workflow_name: 'Outcome Yes Workflow',
        workflow_description: 'Prospect converted — prepare handoff to Legacy Sales.',
        status: 'active',
    },
];
// ============================================================================
// Steps
// ============================================================================
const steps = [
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'new_lead',
        workflow_key: 'new_lead_workflow',
        step_id: 'qualify_lead',
        step_name: 'Qualify Lead',
        step_description: 'Review and qualify the new Legacy lead.',
        step_order: 10,
        gate_enforced: false,
        execution_type: 'manual',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'engaged',
        workflow_key: 'engaged_workflow',
        step_id: 'initial_engagement',
        step_name: 'Initial Engagement',
        step_description: 'Make initial contact with the Legacy lead.',
        step_order: 10,
        gate_enforced: false,
        execution_type: 'manual',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_1',
        workflow_key: 'connect_1_workflow',
        step_id: 'attempt_1',
        step_name: 'Connect Attempt 1',
        step_description: 'First connect attempt.',
        step_order: 10,
        gate_enforced: false,
        execution_type: 'manual',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_2',
        workflow_key: 'connect_2_workflow',
        step_id: 'attempt_2',
        step_name: 'Connect Attempt 2',
        step_description: 'Second connect attempt.',
        step_order: 10,
        gate_enforced: false,
        execution_type: 'manual',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_3',
        workflow_key: 'connect_3_workflow',
        step_id: 'attempt_3',
        step_name: 'Connect Attempt 3',
        step_description: 'Third connect attempt.',
        step_order: 10,
        gate_enforced: false,
        execution_type: 'manual',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'outcome_yes',
        workflow_key: 'outcome_yes_workflow',
        step_id: 'prepare_handoff',
        step_name: 'Prepare Handoff',
        step_description: 'Prepare handoff to Sales Process - Legacy.',
        step_order: 10,
        gate_enforced: false,
        execution_type: 'manual',
        status: 'active',
    },
];
// ============================================================================
// Tasks
// ============================================================================
const tasks = [
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'new_lead',
        workflow_key: 'new_lead_workflow',
        step_id: 'qualify_lead',
        task_id: 'review_lead_source',
        task_name: 'Review Lead Source',
        task_description: 'Review Legacy lead source and qualification criteria.',
        task_order: 10,
        is_required: false,
        is_system_check: false,
        default_owner: 'ADVISOR',
        role_applicability: 'GENERAL',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'engaged',
        workflow_key: 'engaged_workflow',
        step_id: 'initial_engagement',
        task_id: 'log_initial_contact',
        task_name: 'Log Initial Contact',
        task_description: 'Record initial contact details and next steps.',
        task_order: 10,
        is_required: false,
        is_system_check: false,
        default_owner: 'ADVISOR',
        role_applicability: 'GENERAL',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_1',
        workflow_key: 'connect_1_workflow',
        step_id: 'attempt_1',
        task_id: 'log_connect_1',
        task_name: 'Log Connect Attempt 1',
        task_description: 'Record outcome of first connect attempt.',
        task_order: 10,
        is_required: false,
        is_system_check: false,
        default_owner: 'ADVISOR',
        role_applicability: 'GENERAL',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_2',
        workflow_key: 'connect_2_workflow',
        step_id: 'attempt_2',
        task_id: 'log_connect_2',
        task_name: 'Log Connect Attempt 2',
        task_description: 'Record outcome of second connect attempt.',
        task_order: 10,
        is_required: false,
        is_system_check: false,
        default_owner: 'ADVISOR',
        role_applicability: 'GENERAL',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'connect_3',
        workflow_key: 'connect_3_workflow',
        step_id: 'attempt_3',
        task_id: 'log_connect_3',
        task_name: 'Log Connect Attempt 3',
        task_description: 'Record outcome of third connect attempt.',
        task_order: 10,
        is_required: false,
        is_system_check: false,
        default_owner: 'ADVISOR',
        role_applicability: 'GENERAL',
        status: 'active',
    },
    {
        pipeline_key: 'PROSPECT_LEGACY',
        stage_id: 'outcome_yes',
        workflow_key: 'outcome_yes_workflow',
        step_id: 'prepare_handoff',
        task_id: 'create_sales_instance',
        task_name: 'Create Sales Instance',
        task_description: 'Trigger handoff to SALES_LEGACY pipeline.',
        task_order: 10,
        is_required: true,
        is_system_check: false,
        default_owner: 'ADVISOR',
        role_applicability: 'GENERAL',
        status: 'active',
    },
];
// ============================================================================
// Export
// ============================================================================
exports.PROSPECT_LEGACY_CONFIG = {
    pipeline,
    stages,
    workflows,
    steps,
    tasks,
};
