/**
 * SALES_LEGACY pipeline config.
 * 6 stages — Aprille's "It's Time Series."
 * Each stage has a specific team owner (Team Caroline, Team Jennifer, Mo Dadkah).
 */

import type {
  FlowPipelineDef,
  FlowStageDef,
  FlowWorkflowDef,
  FlowStepDef,
  FlowTaskTemplateDef,
} from '../types'

// ============================================================================
// Pipeline
// ============================================================================

const pipeline: FlowPipelineDef = {
  pipeline_key: 'SALES_LEGACY',
  pipeline_name: 'Sales Process - Legacy',
  description: 'Legacy services sales pipeline (Its Time Series). Estate planning intake through notary execution.',
  portal: 'PRODASHX',
  domain: 'LEGACY',
  default_view: 'kanban',
  icon: 'family_restroom',
  status: 'active',
  created_at: '2026-03-13T00:00:00.000Z',
  updated_at: '2026-03-13T00:00:00.000Z',
}

// ============================================================================
// Stages
// ============================================================================

const stages: FlowStageDef[] = [
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'legacy_intro',
    stage_name: 'Legacy Intro',
    stage_description: 'Schedule intro call, explain Its Time Series process.',
    stage_order: 10,
    stage_color: 'blue',
    gate_enforced: false,
    has_workflow: true,
    ghl_stage_id: 'legacy_intro',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    stage_name: 'Intake + Schedule',
    stage_description: 'Gather estate docs, schedule inventory session.',
    stage_order: 20,
    stage_color: 'cyan',
    gate_enforced: false,
    has_workflow: true,
    ghl_stage_id: 'intake_schedule',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    stage_name: 'Inventory',
    stage_description: 'Complete asset inventory, catalog existing documents. Team Caroline + LSA.',
    stage_order: 30,
    stage_color: 'yellow',
    gate_enforced: true,
    has_workflow: true,
    ghl_stage_id: 'inventory',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    stage_name: 'Directives',
    stage_description: 'Draft directives, client review. Team Jennifer + LSA.',
    stage_order: 40,
    stage_color: 'orange',
    gate_enforced: true,
    has_workflow: true,
    ghl_stage_id: 'directives',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    stage_name: 'Attorney Review',
    stage_description: 'Attorney review, revisions, approval. Mo Dadkah + LSA.',
    stage_order: 50,
    stage_color: 'red',
    gate_enforced: true,
    has_workflow: true,
    ghl_stage_id: 'attorney_review',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'notary',
    stage_name: 'Notary',
    stage_description: 'Schedule notary, execute documents, file.',
    stage_order: 60,
    stage_color: 'green',
    gate_enforced: false,
    has_workflow: true,
    ghl_stage_id: 'notary',
    status: 'active',
  },
]

// ============================================================================
// Workflows
// ============================================================================

const workflows: FlowWorkflowDef[] = [
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'legacy_intro',
    workflow_key: 'legacy_intro_workflow',
    workflow_name: 'Legacy Intro Workflow',
    workflow_description: 'Introduction to the Its Time Series process.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    workflow_key: 'intake_schedule_workflow',
    workflow_name: 'Intake + Schedule Workflow',
    workflow_description: 'Gather documents and schedule inventory session.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    workflow_key: 'inventory_workflow',
    workflow_name: 'Inventory Workflow',
    workflow_description: 'Complete asset inventory and document cataloging.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    workflow_key: 'directives_workflow',
    workflow_name: 'Directives Workflow',
    workflow_description: 'Draft and review estate directives.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    workflow_name: 'Attorney Review Workflow',
    workflow_description: 'Attorney review and approval process.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'notary',
    workflow_key: 'notary_workflow',
    workflow_name: 'Notary Workflow',
    workflow_description: 'Schedule notary, execute, and file documents.',
    status: 'active',
  },
]

// ============================================================================
// Steps
// ============================================================================

const steps: FlowStepDef[] = [
  // Legacy Intro
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'legacy_intro',
    workflow_key: 'legacy_intro_workflow',
    step_id: 'intro_call',
    step_name: 'Intro Call',
    step_description: 'Schedule and conduct the introductory call.',
    step_order: 10,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  // Intake + Schedule
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    workflow_key: 'intake_schedule_workflow',
    step_id: 'gather_docs',
    step_name: 'Gather Estate Documents',
    step_description: 'Collect existing estate documents from client.',
    step_order: 10,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    workflow_key: 'intake_schedule_workflow',
    step_id: 'schedule_inventory',
    step_name: 'Schedule Inventory Session',
    step_description: 'Schedule the inventory session with client.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  // Inventory
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    workflow_key: 'inventory_workflow',
    step_id: 'asset_inventory',
    step_name: 'Asset Inventory',
    step_description: 'Complete comprehensive asset inventory.',
    step_order: 10,
    gate_enforced: true,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    workflow_key: 'inventory_workflow',
    step_id: 'doc_catalog',
    step_name: 'Document Catalog',
    step_description: 'Catalog all existing estate documents.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  // Directives
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    workflow_key: 'directives_workflow',
    step_id: 'draft_directives',
    step_name: 'Draft Directives',
    step_description: 'Draft the estate directives.',
    step_order: 10,
    gate_enforced: true,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    workflow_key: 'directives_workflow',
    step_id: 'client_review',
    step_name: 'Client Review',
    step_description: 'Client reviews and approves draft directives.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  // Attorney Review
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    step_id: 'legal_review',
    step_name: 'Attorney Legal Review',
    step_description: 'Attorney reviews documents for legal compliance.',
    step_order: 10,
    gate_enforced: true,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    step_id: 'revisions',
    step_name: 'Revisions',
    step_description: 'Address any revisions from attorney review.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  // Notary
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'notary',
    workflow_key: 'notary_workflow',
    step_id: 'notary_execution',
    step_name: 'Notary Execution',
    step_description: 'Schedule notary, execute documents, file.',
    step_order: 10,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
]

// ============================================================================
// Tasks
// ============================================================================

const tasks: FlowTaskTemplateDef[] = [
  // Legacy Intro
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'legacy_intro',
    workflow_key: 'legacy_intro_workflow',
    step_id: 'intro_call',
    task_id: 'schedule_intro_call',
    task_name: 'Schedule Intro Call',
    task_description: 'Schedule the introductory call to explain the Its Time Series process.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'legacy_intro',
    workflow_key: 'legacy_intro_workflow',
    step_id: 'intro_call',
    task_id: 'explain_its_process',
    task_name: 'Explain ITS Process',
    task_description: 'Walk client through the Its Time Series process and timeline.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'legacy_intro',
    workflow_key: 'legacy_intro_workflow',
    step_id: 'intro_call',
    task_id: 'send_its_welcome',
    task_name: 'Send ITS Welcome Packet',
    task_description: 'Send the Its Time Series welcome packet with overview materials.',
    task_order: 30,
    is_required: false,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // Intake + Schedule
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    workflow_key: 'intake_schedule_workflow',
    step_id: 'gather_docs',
    task_id: 'collect_existing_estate_docs',
    task_name: 'Collect Existing Estate Documents',
    task_description: 'Gather existing wills, trusts, powers of attorney, and other estate docs.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    workflow_key: 'intake_schedule_workflow',
    step_id: 'gather_docs',
    task_id: 'collect_beneficiary_info',
    task_name: 'Collect Beneficiary Information',
    task_description: 'Gather beneficiary designations and contact information.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'intake_schedule',
    workflow_key: 'intake_schedule_workflow',
    step_id: 'schedule_inventory',
    task_id: 'schedule_inventory_session',
    task_name: 'Schedule Inventory Session',
    task_description: 'Schedule the asset inventory session with the client.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // Inventory (Team Caroline + LSA)
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    workflow_key: 'inventory_workflow',
    step_id: 'asset_inventory',
    task_id: 'complete_asset_inventory',
    task_name: 'Complete Asset Inventory',
    task_description: 'Conduct comprehensive asset inventory with the client.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'ASSET_COORDINATOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    workflow_key: 'inventory_workflow',
    step_id: 'asset_inventory',
    task_id: 'verify_asset_completeness',
    task_name: 'Verify Asset Completeness',
    task_description: 'Cross-reference inventory against known accounts and policies.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'LSA',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'inventory',
    workflow_key: 'inventory_workflow',
    step_id: 'doc_catalog',
    task_id: 'catalog_existing_docs',
    task_name: 'Catalog Existing Documents',
    task_description: 'Catalog all existing estate documents and identify gaps.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'ASSET_COORDINATOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // Directives (Team Jennifer + LSA)
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    workflow_key: 'directives_workflow',
    step_id: 'draft_directives',
    task_id: 'draft_estate_directives',
    task_name: 'Draft Estate Directives',
    task_description: 'Draft the estate planning directives based on inventory.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'DIRECTIVE_SPECIALIST',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    workflow_key: 'directives_workflow',
    step_id: 'draft_directives',
    task_id: 'prepare_directive_summary',
    task_name: 'Prepare Directive Summary',
    task_description: 'Prepare a client-friendly summary of the drafted directives.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'LSA',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'directives',
    workflow_key: 'directives_workflow',
    step_id: 'client_review',
    task_id: 'client_directive_review',
    task_name: 'Client Reviews Directives',
    task_description: 'Client reviews drafted directives and provides feedback.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'DIRECTIVE_SPECIALIST',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // Attorney Review (Mo Dadkah + LSA)
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    step_id: 'legal_review',
    task_id: 'submit_to_attorney',
    task_name: 'Submit to Attorney',
    task_description: 'Submit directives to Mo Dadkah for legal review.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'LSA',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    step_id: 'legal_review',
    task_id: 'attorney_legal_review',
    task_name: 'Attorney Legal Review',
    task_description: 'Attorney reviews documents for legal sufficiency and compliance.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'ATTORNEY_REVIEWER',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    step_id: 'revisions',
    task_id: 'address_revisions',
    task_name: 'Address Attorney Revisions',
    task_description: 'Address any revisions required from attorney review.',
    task_order: 30,
    is_required: false,
    is_system_check: false,
    default_owner: 'LSA',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'attorney_review',
    workflow_key: 'attorney_review_workflow',
    step_id: 'revisions',
    task_id: 'attorney_final_approval',
    task_name: 'Attorney Final Approval',
    task_description: 'Attorney provides final approval on all documents.',
    task_order: 40,
    is_required: true,
    is_system_check: false,
    default_owner: 'ATTORNEY_REVIEWER',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // Notary
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'notary',
    workflow_key: 'notary_workflow',
    step_id: 'notary_execution',
    task_id: 'schedule_notary',
    task_name: 'Schedule Notary',
    task_description: 'Schedule the notary signing session.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'notary',
    workflow_key: 'notary_workflow',
    step_id: 'notary_execution',
    task_id: 'execute_documents',
    task_name: 'Execute Documents',
    task_description: 'Execute all estate documents at the notary signing.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_LEGACY',
    stage_id: 'notary',
    workflow_key: 'notary_workflow',
    step_id: 'notary_execution',
    task_id: 'file_documents',
    task_name: 'File Executed Documents',
    task_description: 'File all executed documents in the client ACF folder.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'SPC',
    role_applicability: 'GENERAL',
    status: 'active',
  },
]

// ============================================================================
// Export
// ============================================================================

export const SALES_LEGACY_CONFIG = {
  pipeline,
  stages,
  workflows,
  steps,
  tasks,
} as const
