/**
 * SALES_RETIREMENT pipeline config — The Big One.
 * Primary B2C sales pipeline with 5 color-coded stages.
 * Yellow stage has dynamic casework tasks by product line (role_applicability).
 */

import type {
  FlowPipelineDef,
  FlowStageDef,
  FlowWorkflowDef,
  FlowStepDef,
  FlowTaskTemplateDef,
} from '../types'

// ============================================================================
// Pipeline
// ============================================================================

const pipeline: FlowPipelineDef = {
  pipeline_key: 'SALES_RETIREMENT',
  pipeline_name: 'Sales Process - Retirement',
  description: 'Primary B2C sales pipeline. 5 color-coded stages from Discovery through A+R Close.',
  portal: 'PRODASHX',
  domain: 'RETIREMENT',
  default_view: 'kanban',
  icon: 'trending_up',
  status: 'active',
  created_at: '2026-03-13T00:00:00.000Z',
  updated_at: '2026-03-13T00:00:00.000Z',
}

// ============================================================================
// Stages
// ============================================================================

const stages: FlowStageDef[] = [
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    stage_name: 'Discovery',
    stage_description: 'Book discovery meeting, gather data and authorizations.',
    stage_order: 10,
    stage_color: 'orange',
    gate_enforced: false,
    has_workflow: true,
    ghl_stage_id: 'discovery',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    stage_name: 'Data Foundation',
    stage_description: '8 DEX forms: AI3, COMRA, Life Auth, Wealth Auth, HIPAA, SS Intake, Expenses, Fin Data Req.',
    stage_order: 20,
    stage_color: 'blue',
    gate_enforced: true,
    has_workflow: true,
    ghl_stage_id: 'data_foundation',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    stage_name: 'Case Building',
    stage_description: 'Per-product casework tasks. Dynamic by product line (Investment, Medicare, Life, Annuity).',
    stage_order: 30,
    stage_color: 'yellow',
    gate_enforced: true,
    has_workflow: true,
    ghl_stage_id: 'case_building',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    stage_name: 'Close Ready',
    stage_description: 'All reports complete. Schedule Analysis & Recommendation meeting.',
    stage_order: 40,
    stage_color: 'green',
    gate_enforced: true,
    has_workflow: true,
    ghl_stage_id: 'close_ready',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    stage_name: 'A+R / Close',
    stage_description: 'Leadership review. Final close or stall/loss tracking.',
    stage_order: 50,
    stage_color: 'red',
    gate_enforced: false,
    has_workflow: true,
    ghl_stage_id: 'ar_close',
    status: 'active',
  },
]

// ============================================================================
// Workflows (one per stage)
// ============================================================================

const workflows: FlowWorkflowDef[] = [
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    workflow_name: 'Discovery Workflow',
    workflow_description: 'Initial discovery — data gathering and authorization collection.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    workflow_name: 'Data Foundation Workflow',
    workflow_description: 'Complete all 8 DEX forms for client data foundation.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    workflow_name: 'Case Building Workflow',
    workflow_description: 'Product-specific casework tasks — dynamic by product line.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    workflow_name: 'Close Ready Workflow',
    workflow_description: 'Final report assembly and A+R meeting scheduling.',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    workflow_key: 'ar_close_workflow',
    workflow_name: 'A+R Close Workflow',
    workflow_description: 'Leadership review, final close decision.',
    status: 'active',
  },
]

// ============================================================================
// Steps
// ============================================================================

const steps: FlowStepDef[] = [
  // --- Discovery ---
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'initial_contact',
    step_name: 'Initial Contact',
    step_description: 'Book the discovery meeting and prepare.',
    step_order: 10,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'gather_data',
    step_name: 'Gather Data & Authorizations',
    step_description: 'Collect initial authorizations and basic client data.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },

  // --- Data Foundation ---
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    step_name: 'DEX Form Completion',
    step_description: 'Complete all 8 DEX forms for full data foundation.',
    step_order: 10,
    gate_enforced: true,
    execution_type: 'manual',
    status: 'active',
  },

  // --- Case Building ---
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'general_casework',
    step_name: 'General Casework',
    step_description: 'Verify authorizations, confirm data, assemble Case Central.',
    step_order: 10,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'investment_casework',
    step_name: 'Investment Casework',
    step_description: 'Pull statements, Gradient reports, Morningstar, build recommendation.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'que_workbench',
    que_config: { profile_id: 'QUE_INVESTMENT', auto_create_session: true },
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'medicare_casework',
    step_name: 'Medicare Casework',
    step_description: 'Run QUE-Medicare quoting, generate recommendation.',
    step_order: 30,
    gate_enforced: false,
    execution_type: 'que_workbench',
    que_config: { profile_id: 'QUE_MEDICARE', auto_create_session: true },
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'life_casework',
    step_name: 'Life Casework',
    step_description: 'Pull life policies, IFI analysis, carrier comparison.',
    step_order: 40,
    gate_enforced: false,
    execution_type: 'que_workbench',
    que_config: { profile_id: 'QUE_LIFE', auto_create_session: true },
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'annuity_casework',
    step_name: 'Annuity Casework',
    step_description: 'Pull annuity statements, income projections, FIA/MYGA comparison.',
    step_order: 50,
    gate_enforced: false,
    execution_type: 'que_workbench',
    que_config: { profile_id: 'QUE_ANNUITY', auto_create_session: true },
    status: 'active',
  },

  // --- Close Ready ---
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    step_id: 'report_assembly',
    step_name: 'Report Assembly',
    step_description: 'Verify all reports are complete and assembled.',
    step_order: 10,
    gate_enforced: true,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    step_id: 'schedule_ar',
    step_name: 'Schedule A+R Meeting',
    step_description: 'Schedule the Analysis & Recommendation meeting with client.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },

  // --- A+R / Close ---
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    workflow_key: 'ar_close_workflow',
    step_id: 'leadership_review',
    step_name: 'Leadership Review',
    step_description: 'Leadership reviews case and approves close strategy.',
    step_order: 10,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    workflow_key: 'ar_close_workflow',
    step_id: 'final_close',
    step_name: 'Final Close',
    step_description: 'Execute close, or record stall/loss outcome.',
    step_order: 20,
    gate_enforced: false,
    execution_type: 'manual',
    status: 'active',
  },
]

// ============================================================================
// Tasks (30+ across all stages, with role_applicability for Yellow Stage)
// ============================================================================

const tasks: FlowTaskTemplateDef[] = [
  // ---- Discovery Stage ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'initial_contact',
    task_id: 'book_discovery',
    task_name: 'Book Discovery Meeting',
    task_description: 'Schedule the initial discovery meeting with the client.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'initial_contact',
    task_id: 'send_welcome_packet',
    task_name: 'Send Welcome Packet',
    task_description: 'Send the new client welcome packet with intro materials.',
    task_order: 20,
    is_required: false,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'gather_data',
    task_id: 'collect_auth_forms',
    task_name: 'Collect Authorization Forms',
    task_description: 'Gather signed authorization forms for data access.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'gather_data',
    task_id: 'gather_basic_data',
    task_name: 'Gather Basic Client Data',
    task_description: 'Collect essential client info: demographics, goals, risk tolerance.',
    task_order: 40,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'discovery',
    workflow_key: 'discovery_workflow',
    step_id: 'gather_data',
    task_id: 'create_acf_folder',
    task_name: 'Create ACF Folder',
    task_description: 'Create the Active Client File folder in Drive.',
    task_order: 50,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // ---- Data Foundation Stage (Blue) ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_ai3',
    task_name: 'Complete AI3 Form',
    task_description: 'Agent Illustration Input form (AI3) — client financial profile.',
    task_order: 10,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'AI3' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_comra',
    task_name: 'Complete COMRA Form',
    task_description: 'Comprehensive Risk Assessment form.',
    task_order: 20,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'COMRA' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_life_auth',
    task_name: 'Complete Life Authorization',
    task_description: 'Life insurance data authorization form.',
    task_order: 30,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'LIFE_AUTH' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_wealth_auth',
    task_name: 'Complete Wealth Authorization',
    task_description: 'Wealth/investment data authorization form.',
    task_order: 40,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'WEALTH_AUTH' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_hipaa',
    task_name: 'Complete HIPAA Authorization',
    task_description: 'HIPAA authorization for health data access.',
    task_order: 50,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'HIPAA' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_ss_intake',
    task_name: 'Complete SS Intake Form',
    task_description: 'Social Security intake and benefits review form.',
    task_order: 60,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'SS_INTAKE' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_expenses',
    task_name: 'Complete Expenses Form',
    task_description: 'Monthly expense worksheet.',
    task_order: 70,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'EXPENSES' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'data_foundation',
    workflow_key: 'data_foundation_workflow',
    step_id: 'dex_forms',
    task_id: 'form_fin_data_req',
    task_name: 'Complete Financial Data Request',
    task_description: 'Financial data request form for third-party data.',
    task_order: 80,
    is_required: true,
    is_system_check: true,
    check_type: 'ALL_FORMS_CHECKED',
    check_config: JSON.stringify({ form_type: 'FIN_DATA_REQ' }),
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // ---- Case Building Stage (Yellow) — GENERAL tasks ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'general_casework',
    task_id: 'verify_all_auths',
    task_name: 'Verify All Authorizations Signed',
    task_description: 'Confirm all required authorizations are signed and on file.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'general_casework',
    task_id: 'confirm_data_complete',
    task_name: 'Confirm All Data Collected',
    task_description: 'Verify all client data is complete and accurate.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'general_casework',
    task_id: 'assemble_case_central',
    task_name: 'Assemble Case Central Package',
    task_description: 'Compile all client data, reports, and recommendations into Case Central.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // ---- Case Building Stage (Yellow) — INVESTMENT tasks ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'investment_casework',
    task_id: 'pull_investment_statements',
    task_name: 'Pull Current Investment Statements',
    task_description: 'Retrieve current investment account statements from custodians.',
    task_order: 40,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'INVESTMENT',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'investment_casework',
    task_id: 'order_gradient_reports',
    task_name: 'Order Gradient Reports',
    task_description: 'Submit request for Gradient portfolio analysis reports.',
    task_order: 50,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'INVESTMENT',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'investment_casework',
    task_id: 'review_morningstar',
    task_name: 'Review Morningstar Analysis',
    task_description: 'Review Morningstar fund analysis and performance data.',
    task_order: 60,
    is_required: false,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'INVESTMENT',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'investment_casework',
    task_id: 'build_investment_recommendation',
    task_name: 'Build Portfolio Recommendation',
    task_description: 'Create portfolio recommendation based on analysis and client goals.',
    task_order: 70,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'INVESTMENT',
    status: 'active',
  },

  // ---- Case Building Stage (Yellow) — MEDICARE tasks ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'medicare_casework',
    task_id: 'run_que_medicare',
    task_name: 'Run QUE-Medicare Quoting',
    task_description: 'Execute QUE-Medicare quoting engine for plan comparison.',
    task_order: 80,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'MEDICARE',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'medicare_casework',
    task_id: 'generate_medicare_recommendation',
    task_name: 'Generate Medicare Recommendation',
    task_description: 'Build Medicare plan recommendation based on quoting results.',
    task_order: 90,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'MEDICARE',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'medicare_casework',
    task_id: 'client_review_medicare',
    task_name: 'Client Review of Medicare Options',
    task_description: 'Present Medicare options to client and confirm selection.',
    task_order: 100,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'MEDICARE',
    status: 'active',
  },

  // ---- Case Building Stage (Yellow) — LIFE tasks ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'life_casework',
    task_id: 'pull_life_policies',
    task_name: 'Pull Current Life Policy Details',
    task_description: 'Retrieve current life insurance policy data and in-force illustrations.',
    task_order: 110,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'LIFE',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'life_casework',
    task_id: 'run_ifi_analysis',
    task_name: 'Run IFI Analysis',
    task_description: 'Run In-Force Illustration analysis on existing life policies.',
    task_order: 120,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'LIFE',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'life_casework',
    task_id: 'compare_life_carriers',
    task_name: 'Compare Carrier Options',
    task_description: 'Compare life insurance carrier options based on client profile.',
    task_order: 130,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'LIFE',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'life_casework',
    task_id: 'build_life_recommendation',
    task_name: 'Build Life Recommendation',
    task_description: 'Create life insurance recommendation based on analysis.',
    task_order: 140,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'LIFE',
    status: 'active',
  },

  // ---- Case Building Stage (Yellow) — ANNUITY tasks ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'annuity_casework',
    task_id: 'pull_annuity_statements',
    task_name: 'Pull Current Annuity Statements',
    task_description: 'Retrieve current annuity account statements.',
    task_order: 150,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'ANNUITY',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'annuity_casework',
    task_id: 'run_income_projections',
    task_name: 'Run Income Projections',
    task_description: 'Execute income projection models for annuity options.',
    task_order: 160,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'ANNUITY',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'annuity_casework',
    task_id: 'compare_fia_myga',
    task_name: 'Compare FIA/MYGA Options',
    task_description: 'Compare Fixed Index Annuity and Multi-Year Guaranteed Annuity options.',
    task_order: 170,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'ANNUITY',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'case_building',
    workflow_key: 'case_building_workflow',
    step_id: 'annuity_casework',
    task_id: 'build_annuity_recommendation',
    task_name: 'Build Annuity Recommendation',
    task_description: 'Create annuity recommendation based on income projections and client goals.',
    task_order: 180,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'ANNUITY',
    status: 'active',
  },

  // ---- Close Ready Stage (Green) ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    step_id: 'report_assembly',
    task_id: 'verify_all_reports_complete',
    task_name: 'Verify All Reports Complete',
    task_description: 'Confirm every product-line report is finalized and assembled.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    step_id: 'report_assembly',
    task_id: 'verify_case_central_package',
    task_name: 'Verify Case Central Package',
    task_description: 'Ensure Case Central package is complete with all recommendations.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    step_id: 'schedule_ar',
    task_id: 'schedule_ar_meeting',
    task_name: 'Schedule A+R Meeting',
    task_description: 'Schedule the Analysis & Recommendation meeting with the client.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'close_ready',
    workflow_key: 'close_ready_workflow',
    step_id: 'schedule_ar',
    task_id: 'prep_ar_presentation',
    task_name: 'Prepare A+R Presentation',
    task_description: 'Prepare the presentation materials for the A+R meeting.',
    task_order: 40,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },

  // ---- A+R / Close Stage (Red) ----
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    workflow_key: 'ar_close_workflow',
    step_id: 'leadership_review',
    task_id: 'leadership_case_review',
    task_name: 'Leadership Case Review',
    task_description: 'Leadership reviews the complete case and approves the close strategy.',
    task_order: 10,
    is_required: true,
    is_system_check: false,
    default_owner: 'COR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    workflow_key: 'ar_close_workflow',
    step_id: 'final_close',
    task_id: 'conduct_ar_meeting',
    task_name: 'Conduct A+R Meeting',
    task_description: 'Present Analysis & Recommendation to the client.',
    task_order: 20,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
  {
    pipeline_key: 'SALES_RETIREMENT',
    stage_id: 'ar_close',
    workflow_key: 'ar_close_workflow',
    step_id: 'final_close',
    task_id: 'record_outcome',
    task_name: 'Record Close Outcome',
    task_description: 'Record final outcome: Won, Stalled, or Lost with reason.',
    task_order: 30,
    is_required: true,
    is_system_check: false,
    default_owner: 'ADVISOR',
    role_applicability: 'GENERAL',
    status: 'active',
  },
]

// ============================================================================
// Export
// ============================================================================

export const SALES_RETIREMENT_CONFIG = {
  pipeline,
  stages,
  workflows,
  steps,
  tasks,
} as const
