/**
 * ASSEMBLE_OUTPUT — Super Tool (TRK-13392)
 *
 * Orchestrates all 5 Yellow Stage outputs into ACF B4.
 * This is the final step — collects everything generated by the pipeline
 * and prepares it for filing via DEX tools.
 *
 * The actual Drive filing (html-to-pdf, file-to-acf) happens through DEX tools
 * which are async/side-effectful. This super tool PREPARES the package.
 *
 * Outputs:
 *   1. AI3 PDF (HTML) — from generate-ai3-pdf
 *   2. Reports + IFIs — references to existing carrier docs
 *   3. Product Illustrations — references to existing illustrations
 *   4. Casework Components — from GENERATE_CASEWORK
 *   5. Factfinder — from generate-factfinder
 */

import type { AnalysisResult, SuperToolHousehold } from './types'
import type { CaseworkOutput } from './generate-casework'
import { generateAi3Pdf } from '../generators/generate-ai3-pdf'
import { generateFactfinder } from '../generators/generate-factfinder'

export interface AssembledDocument {
  /** Document identifier */
  name: string
  /** Output number (1-5) */
  outputNumber: 1 | 2 | 3 | 4 | 5
  /** Content type */
  contentType: 'html' | 'reference'
  /** HTML content (for html type) */
  html?: string
  /** Reference description (for reference type) */
  referenceNote?: string
}

export interface AssembleOutputResult {
  success: boolean
  householdId: string
  clientNames: string
  documents: AssembledDocument[]
  /** Summary of what was assembled */
  summary: {
    output1_ai3: boolean
    output2_reports: boolean
    output3_illustrations: boolean
    output4_casework: number
    output5_factfinder: boolean
    totalDocuments: number
  }
}

export function assembleOutput(
  household: SuperToolHousehold,
  analyses: AnalysisResult[],
  caseworkOutputs: CaseworkOutput[],
  preparedBy: string,
  preparedDate: string,
  authForms: Array<'life' | 'wealth' | 'its'> = ['life', 'wealth']
): AssembleOutputResult {
  const clientNames = household.members.map((m) => m.name).join(' & ')
  const documents: AssembledDocument[] = []

  // Output 1: AI3 PDF
  const ai3Html = generateAi3Pdf({
    household,
    analyses,
    preparedBy,
    preparedDate,
  })
  documents.push({
    name: `AI3 — ${clientNames}`,
    outputNumber: 1,
    contentType: 'html',
    html: ai3Html,
  })

  // Output 2: Reports + In-Force Illustrations (references — actual docs are in ACF)
  documents.push({
    name: `Reports & IFIs — ${clientNames}`,
    outputNumber: 2,
    contentType: 'reference',
    referenceNote: 'Collect Ameritas IFIs, Signal outputs (RightCapital, Riskalyze), and carrier annual statements from ACF. Use UL Case Matrix for illustration instructions.',
  })

  // Output 3: Product Illustrations (references — generated via WinFlex/carrier tools)
  documents.push({
    name: `Product Illustrations — ${clientNames}`,
    outputNumber: 3,
    contentType: 'reference',
    referenceNote: 'Income Comparison, GROWTH MAX, FE v TERM v IUL, and carrier-specific illustrations. Generated via WinFlex and carrier portals.',
  })

  // Output 4: Casework Components
  for (const cw of caseworkOutputs) {
    documents.push({
      name: `${cw.type.replace(/_/g, ' ').toUpperCase()} — Summary`,
      outputNumber: 4,
      contentType: 'html',
      html: cw.summaryHtml,
    })
    documents.push({
      name: `${cw.type.replace(/_/g, ' ').toUpperCase()} — Detail`,
      outputNumber: 4,
      contentType: 'html',
      html: cw.detailHtml,
    })
  }

  // Output 5: Factfinder
  const factfinderHtml = generateFactfinder({
    household,
    authForms,
    preparedBy,
    preparedDate,
  })
  documents.push({
    name: `RPI Factfinder — ${clientNames}`,
    outputNumber: 5,
    contentType: 'html',
    html: factfinderHtml,
  })

  return {
    success: true,
    householdId: household.id,
    clientNames,
    documents,
    summary: {
      output1_ai3: true,
      output2_reports: true,
      output3_illustrations: true,
      output4_casework: caseworkOutputs.length,
      output5_factfinder: true,
      totalDocuments: documents.length,
    },
  }
}
